language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - pecl install swoole -f
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: vendor/bin/phpunit
